# Generated by Django 4.2.7 on 2024-07-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default='1Kg', max_digits=10, null=True),
        ),
    ]
