# Generated by Django 4.2.7 on 2024-07-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
